import type { Metadata } from "next";
import "./globals.css";
import {Poppins} from "next/font/google"
import Header from "./components/Header";
import Footer from "./components/Footer";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins'
}
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body
        className={poppins.variable}
      >
        <div className="min-h-screen flex flex-col font-poppins">
          <Header />
          <main className=" w-full flex-grow  ">
            {children}
          </main>
          <Footer />

        </div>
        

      </body>
    </html>
  );
}
